name: Build OpenJDK21 for Android

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
  - cron: "20 5 2,9,16,23 * *"

jobs:
  build_android:
    strategy:
      matrix:
        arch: [ "aarch32", "aarch64", "x86", "x86_64" ]
      fail-fast: false

    name: "Build for Android ${{matrix.arch}}"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1    
    - name: set up JDK 21
      uses: actions/setup-java@v4.1.0
      with:
        java-version: 21
        distribution: temurin
    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt -y install autoconf python3 python-is-python3 unzip zip systemtap-sdt-dev libxtst-dev libasound2-dev libelf-dev libfontconfig1-dev libx11-dev libxext-dev libxrandr-dev libxrender-dev libxtst-dev libxt-dev
        git clone --depth 1 --branch buildjre21 https://github.com/Vera-Firefly/android-openjdk-build
    - name: Build with CI build script
      run: |
        cd android-openjdk-build
        bash "ci_build_arch_${{matrix.arch}}.sh"
    - name: Upload JDK build output
      uses: actions/upload-artifact@v4.3.1
      with:
        name: "jdk21-${{matrix.arch}}"
        path: android-openjdk-build/jdk21*.tar.xz
    - name: Upload JRE build output
      uses: actions/upload-artifact@v4.3.1
      with:
        name: 'jre21-${{matrix.arch}}'
        path: android-openjdk-build/jre21*.tar.xz
    - name: Upload JRE debuginfo build output
      uses: actions/upload-artifact@v4.3.1
      with:
        name: "jre21-debuginfo-${{matrix.arch}}"
        path: android-openjdk-build/dizout

  pojav:
    needs: build_android
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1
    - name: Get jre21-aarch32
      uses: actions/download-artifact@v4.1.4
      with:
        name: jre21-aarch32
        path: android-openjdk-build/pojav
    - name: Get jre21-aarch64
      uses: actions/download-artifact@v4.1.4
      with:
        name: jre21-aarch64
        path: android-openjdk-build/pojav
    - name: Get jre21-x86
      uses: actions/download-artifact@v4.1.4
      with:
        name: jre21-x86
        path: android-openjdk-build/pojav
    - name: Get jre21-x86_64
      uses: actions/download-artifact@v4.1.4
      with:
        name: jre21-x86_64
        path: android-openjdk-build/pojav
    - name: Repack JRE
      run: |
        cd android-openjdk-build
        bash "android-openjdk-build/repackjre.sh" $GITHUB_WORKSPACE/android-openjdk-build/pojav $GITHUB_WORKSPACE/android-openjdk-build/pojav/jre21-pojav
    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.1
      with:
          name: jre21-pojav
          path: android-openjdk-build/pojav/jre21-pojav/*
