name: Push Jre and JSPH

on:
  workflow_dispatch:

jobs:
  upload_pojav_jre:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get libjsph 25
        uses: dawidd6/action-download-artifact@master
        with:
          workflow: buildjre25.yml
          path: jsph
          workflow_conclusion: success
          repo: Vera-Firefly/android-openjdk-autobuild
          branch: main
          name: jsph-25
          
      - name: Upload libjsph
        uses: actions/upload-artifact@main
        with:
          name: libjsph
          path: jsph/*
